import { staff } from 'src/app/features/sistem-data/models/staff.model';

export const dummyData: staff[] = [
	{
		id: 1,
		name: 'Ana',
		lastname: 'Pérez',
		username: 'aperez',
		email: 'ana.perez@example.com',
		phone: '+1-555-1234',
		status: true,
		photo: 'https://example.com/profiles/aperez.jpg',
	},
	{
		id: 2,
		name: 'Luis',
		lastname: 'Rodríguez',
		username: 'lrodriguez',
		email: 'luis.rodriguez@example.com',
		phone: '+1-555-5678',
		status: false,
		photo: 'https://example.com/profiles/lrodriguez.jpg',
	},
	{
		id: 3,
		name: 'María',
		lastname: 'Gómez',
		username: 'mgomez',
		email: 'maria.gomez@example.com',
		phone: '+1-555-9012',
		status: true,
		photo: 'https://example.com/profiles/mgomez.jpg',
	},
	{
		id: 4,
		name: 'Carlos',
		lastname: 'Díaz',
		username: 'cdiaz',
		email: 'carlos.diaz@example.com',
		phone: '+1-555-3456',
		status: true,
		photo: 'https://example.com/profiles/cdiaz.jpg',
	},
	{
		id: 5,
		name: 'Lucía',
		lastname: 'Torres',
		username: 'ltorres',
		email: 'lucia.torres@example.com',
		phone: '+1-555-7890',
		status: false,
		photo: 'https://example.com/profiles/ltorres.jpg',
	},
	{
		id: 6,
		name: 'Jorge',
		lastname: 'Romero',
		username: 'jromero',
		email: 'jorge.romero@example.com',
		phone: '+1-555-6543',
		status: true,
		photo: 'https://example.com/profiles/jromero.jpg',
	},
	{
		id: 7,
		name: 'Paula',
		lastname: 'Herrera',
		username: 'pherrera',
		email: 'paula.herrera@example.com',
		phone: '+1-555-3210',
		status: true,
		photo: 'https://example.com/profiles/pherrera.jpg',
	},
	{
		id: 8,
		name: 'Miguel',
		lastname: 'Castro Corrales',
		username: 'mcastro',
		email: 'miguel.castro@example.com',
		phone: '+1-555-2109',
		status: false,
		photo: 'https://example.com/profiles/mcastro.jpg',
	},
	{
		id: 9,
		name: 'Sofía Lorena',
		lastname: 'Vargas',
		username: 'svargas',
		email: 'sofia.vargas@example.com',
		phone: '+1-555-1324',
		status: true,
		photo: 'https://example.com/profiles/svargas.jpg',
	},
	{
		id: 10,
		name: 'Andrés Lautaro',
		lastname: 'León Del Pino',
		username: 'aleon',
		email: 'andres.leon@example.com',
		phone: '+1-555-7865',
		status: true,
		photo: 'https://example.com/profiles/aleon.jpg',
	},
	{
		id: 11,
		name: 'Valentina Rocio',
		lastname: 'Molina',
		username: 'vmolina',
		email: 'valentina.molina@example.com',
		phone: '+1-555-9876',
		status: true,
		photo: 'https://example.com/profiles/vmolina.jpg',
	},
	{
		id: 12,
		name: 'Tomás',
		lastname: 'Ríos',
		username: 'trios',
		email: 'tomas.rios@example.com',
		phone: '+1-555-1122',
		status: false,
		photo: 'https://example.com/profiles/trios.jpg',
	},
	{
		id: 13,
		name: 'Camila',
		lastname: 'Navarro',
		username: 'cnavarro',
		email: 'camila.navarro@example.com',
		phone: '+1-555-3344',
		status: true,
		photo: 'https://example.com/profiles/cnavarro.jpg',
	},
	{
		id: 14,
		name: 'Diego',
		lastname: 'Fuentes Corvera',
		username: 'dfuentes',
		email: 'diego.fuentes@example.com',
		phone: '+1-555-5566',
		status: false,
		photo: 'https://example.com/profiles/dfuentes.jpg',
	},
	{
		id: 15,
		name: 'Renata',
		lastname: 'Salazar Sanchez',
		username: 'rsalazar',
		email: 'renata.salazar@example.com',
		phone: '+1-555-7788',
		status: true,
		photo: 'https://example.com/profiles/rsalazar.jpg',
	},
];
