import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AngularSvgIconModule } from 'angular-svg-icon';
@Component({
	selector: 'app-logos',
	standalone: true,
	imports: [CommonModule, AngularSvgIconModule],
	templateUrl: './logos.component.html',
	styleUrls: ['./logos.component.scss'],
})
export class LogosComponent {
	logos = [
		{ name: 'arrow-long-left', src: 'assets/icons/heroicons/outline/arrow-long-left.svg' },
		{ name: 'arrow-long-right', src: 'assets/icons/heroicons/outline/arrow-long-right.svg' },
		{ name: 'arrow-sm-right', src: 'assets/icons/heroicons/outline/arrow-sm-right.svg' },
		{ name: 'arrow-sm-up', src: 'assets/icons/heroicons/outline/arrow-sm-up.svg' },
		{ name: 'arrow-up', src: 'assets/icons/heroicons/outline/arrow-up.svg' },
		{ name: 'arrow-down', src: 'assets/icons/heroicons/outline/arrow-down.svg' },
		{ name: 'bell', src: 'assets/icons/heroicons/outline/bell.svg' },
		{ name: 'bookmark', src: 'assets/icons/heroicons/outline/bookmark.svg' },
		{ name: 'chart-pie', src: 'assets/icons/heroicons/outline/chart-pie.svg' },
		{ name: 'cog-6-tooth', src: 'assets/icons/heroicons/outline/cog-6-tooth.svg' },
		{ name: 'cog', src: 'assets/icons/heroicons/outline/cog.svg' },
		{ name: 'cube', src: 'assets/icons/heroicons/outline/cube.svg' },
		{ name: 'cursor-click', src: 'assets/icons/heroicons/outline/cursor-click.svg' },
		{ name: 'dots-horizontal', src: 'assets/icons/heroicons/outline/dots-horizontal.svg' },
		{ name: 'download', src: 'assets/icons/heroicons/outline/download.svg' },
		{ name: 'ellipsis-vertical', src: 'assets/icons/heroicons/outline/ellipsis-vertical.svg' },
		{ name: 'exclamation-triangle', src: 'assets/icons/heroicons/outline/exclamation-triangle.svg' },
		{ name: 'eye-off', src: 'assets/icons/heroicons/outline/eye-off.svg' },
		{ name: 'eye', src: 'assets/icons/heroicons/outline/eye.svg' },
		{ name: 'folder', src: 'assets/icons/heroicons/outline/folder.svg' },
		{ name: 'gift', src: 'assets/icons/heroicons/outline/gift.svg' },
		{ name: 'information-circle', src: 'assets/icons/heroicons/outline/information-circle.svg' },
		{ name: 'lock-closed', src: 'assets/icons/heroicons/outline/lock-closed.svg' },
		{ name: 'logout', src: 'assets/icons/heroicons/outline/logout.svg' },
		{ name: 'magnifying-glass', src: 'assets/icons/heroicons/outline/magnifying-glass.svg' },
		{ name: 'menu', src: 'assets/icons/heroicons/outline/menu.svg' },
		{ name: 'minus', src: 'assets/icons/heroicons/outline/minus.svg' },
		{ name: 'moon', src: 'assets/icons/heroicons/outline/moon.svg' },
		{ name: 'plus', src: 'assets/icons/heroicons/outline/plus.svg' },
		{ name: 'shield-check', src: 'assets/icons/heroicons/outline/shield-check.svg' },
		{ name: 'sun', src: 'assets/icons/heroicons/outline/sun.svg' },
		{ name: 'user-circle', src: 'assets/icons/heroicons/outline/user-circle.svg' },
		{ name: 'users', src: 'assets/icons/heroicons/outline/users.svg' },
		{ name: 'view-grid', src: 'assets/icons/heroicons/outline/view-grid.svg' },
		{ name: 'x', src: 'assets/icons/heroicons/outline/x.svg' },
		{ name: 'chevron-double-left', src: 'assets/icons/heroicons/solid/chevron-double-left.svg' },
		{ name: 'chevron-right', src: 'assets/icons/heroicons/solid/chevron-right.svg' },
		{ name: 'play', src: 'assets/icons/heroicons/solid/play.svg' },
		{ name: 'arrows-shuffle-2', src: 'assets/icons/tablericons/arrows-shuffle-2.svg' },
		{ name: 'headphones', src: 'assets/icons/tablericons/headphones.svg' },
		{ name: 'player-skip-back-filled', src: 'assets/icons/tablericons/player-skip-back-filled.svg' },
		{ name: 'player-skip-forward-filled', src: 'assets/icons/tablericons/player-skip-forward-filled.svg' },
		{ name: 'repeat', src: 'assets/icons/tablericons/repeat.svg' },
		{ name: 'text-direction-ltr', src: 'assets/icons/tablericons/text-direction-ltr.svg' },
		{ name: 'text-direction-rtl', src: 'assets/icons/tablericons/text-direction-rtl.svg' },
		{ name: 'google-logo', src: 'assets/icons/google-logo.svg' },
		{ name: 'logo', src: 'assets/icons/logo.svg' },
		{ name: 'add-1-svgrepo-com', src: 'assets/icons/usericons/add-1-svgrepo-com.svg' },
		{ name: 'add-call-svgrepo-com', src: 'assets/icons/usericons/add-call-svgrepo-com.svg' },
		{ name: 'add-email-svgrepo-com', src: 'assets/icons/usericons/add-email-svgrepo-com.svg' },
		{ name: 'add-file-svgrepo-com', src: 'assets/icons/usericons/add-file-svgrepo-com.svg' },
		{ name: 'add-folder-svgrepo-com', src: 'assets/icons/usericons/add-folder-svgrepo-com.svg' },
		{ name: 'add-note-svgrepo-com', src: 'assets/icons/usericons/add-note-svgrepo-com.svg' },
		{ name: 'add-photo-svgrepo-com', src: 'assets/icons/usericons/add-photo-svgrepo-com.svg' },
		{ name: 'add-svgrepo-com', src: 'assets/icons/usericons/add-svgrepo-com.svg' },
		{ name: 'add-to-cart-svgrepo-com', src: 'assets/icons/usericons/add-to-cart-svgrepo-com.svg' },
		{ name: 'add-to-queue-svgrepo-com', src: 'assets/icons/usericons/add-to-queue-svgrepo-com.svg' },
		{ name: 'delete-2-svgrepo-com', src: 'assets/icons/usericons/delete-2-svgrepo-com.svg' },
		{ name: 'document-update-svgrepo-com', src: 'assets/icons/usericons/document-update-svgrepo-com.svg' },
		{ name: 'download-email-svgrepo-com', src: 'assets/icons/usericons/download-email-svgrepo-com.svg' },
		{ name: 'download-folder-svgrepo-com', src: 'assets/icons/usericons/download-folder-svgrepo-com.svg' },
		{ name: 'download-svgrepo-com', src: 'assets/icons/usericons/download-svgrepo-com.svg' },
		{
			name: 'hand-hold-bank-building-finance-svgrepo-com',
			src: 'assets/icons/usericons/hand-hold-bank-building-finance-svgrepo-com.svg',
		},
		{ name: 'hand-thumbs-down-svgrepo-com', src: 'assets/icons/usericons/hand-thumbs-down-svgrepo-com.svg' },
		{ name: 'hand-thumbs-up-svgrepo-com', src: 'assets/icons/usericons/hand-thumbs-up-svgrepo-com.svg' },
		{ name: 'hand-truck-svgrepo-com', src: 'assets/icons/usericons/hand-truck-svgrepo-com.svg' },
		{ name: 'list-add-svgrepo-com', src: 'assets/icons/usericons/list-add-svgrepo-com.svg' },
		{ name: 'list-check-svgrepo-com', src: 'assets/icons/usericons/list-check-svgrepo-com.svg' },
		{ name: 'list-remove-svgrepo-com', src: 'assets/icons/usericons/list-remove-svgrepo-com.svg' },
		{ name: 'mail-new-svgrepo-com', src: 'assets/icons/usericons/mail-new-svgrepo-com.svg' },
		{ name: 'padlock-close-svgrepo-com', src: 'assets/icons/usericons/padlock-close-svgrepo-com.svg' },
		{ name: 'padlock-open-svgrepo-com', src: 'assets/icons/usericons/padlock-open-svgrepo-com.svg' },
		{ name: 'padlock-outlined-svgrepo-com', src: 'assets/icons/usericons/padlock-outlined-svgrepo-com.svg' },
		{
			name: 'padlock-unlocked-outlined-svgrepo-com',
			src: 'assets/icons/usericons/padlock-unlocked-outlined-svgrepo-com.svg',
		},
		{ name: 'shield-new-svgrepo-com', src: 'assets/icons/usericons/shield-new-svgrepo-com.svg' },
		{ name: 'status-refresh-svgrepo-com', src: 'assets/icons/usericons/status-refresh-svgrepo-com.svg' },
		{ name: 'status-updated-svgrepo-com', src: 'assets/icons/usericons/status-updated-svgrepo-com.svg' },
		{ name: 'tablet-refresh-svgrepo-com', src: 'assets/icons/usericons/tablet-refresh-svgrepo-com.svg' },
		{ name: 'todolist-refresh-svgrepo-com', src: 'assets/icons/usericons/todolist-refresh-svgrepo-com.svg' },
		{ name: 'update-alt-2-svgrepo-com', src: 'assets/icons/usericons/update-alt-2-svgrepo-com.svg' },
		{ name: 'update-alt-svgrepo-com', src: 'assets/icons/usericons/update-alt-svgrepo-com.svg' },
		{ name: 'update-svgrepo-com', src: 'assets/icons/usericons/update-svgrepo-com.svg' },
		{ name: 'upload-cloud-svgrepo-com', src: 'assets/icons/usericons/upload-cloud-svgrepo-com.svg' },
		{ name: 'upload-folder-svgrepo-com', src: 'assets/icons/usericons/upload-folder-svgrepo-com.svg' },
		{ name: 'upload-square-svgrepo-com', src: 'assets/icons/usericons/upload-square-svgrepo-com.svg' },
		{ name: 'upload-svgrepo-com', src: 'assets/icons/usericons/upload-svgrepo-com.svg' },
		{ name: 'warning-circle-svgrepo-com', src: 'assets/icons/usericons/warning-circle-svgrepo-com.svg' },
		{ name: 'check-circle-svgrepo-com', src: 'assets/icons/usericons/check-circle-svgrepo-com.svg' },
		{ name: 'user-profile-avatar-svgrepo-com', src: 'assets/icons/usericons/user-profile-avatar-svgrepo-com.svg' },
		{
			name: 'account-out-person-profile-user-group-svgrepo-com',
			src: 'assets/icons/usericons/account-out-person-profile-user-group-svgrepo-com.svg',
		},
		{
			name: 'account-person-profile-uncheck-user-group-svgrepo-com',
			src: 'assets/icons/usericons/account-person-profile-uncheck-user-group-svgrepo-com.svg',
		},
		{
			name: 'avatar-profile-user-account-person-svgrepo-com',
			src: 'assets/icons/usericons/avatar-profile-user-account-person-svgrepo-com.svg',
		},
		{
			name: 'check-person-profile-user-group-people-svgrepo-com',
			src: 'assets/icons/usericons/check-person-profile-user-group-people-svgrepo-com.svg',
		},
		{
			name: 'calendar-days-svgrepo-com',
			src: 'assets/icons/usericons/calendar-days-svgrepo-com.svg',
		},
		{
			name: 'calendar-xmark-svgrepo-com',
			src: 'assets/icons/usericons/calendar-xmark-svgrepo-com.svg',
		},
		{
			name: 'calendar-lines-pen-svgrepo-com',
			src: 'assets/icons/usericons/calendar-lines-pen-svgrepo-com.svg',
		},
	];
}
